{
  "url": "https://api.github.com/repos/quarkusio/quarkus/issues/20197",
  "repository_url": "https://api.github.com/repos/quarkusio/quarkus",
  "labels_url": "https://api.github.com/repos/quarkusio/quarkus/issues/20197/labels{/name}",
  "comments_url": "https://api.github.com/repos/quarkusio/quarkus/issues/20197/comments",
  "events_url": "https://api.github.com/repos/quarkusio/quarkus/issues/20197/events",
  "html_url": "https://github.com/quarkusio/quarkus/issues/20197",
  "id": 997993398,
  "node_id": "I_kwDOCFbutM47fCu2",
  "number": 20197,
  "title": "Reload of dev-services broken",
  "labels": [
    {
      "id": 985346620,
      "node_id": "MDU6TGFiZWw5ODUzNDY2MjA=",
      "url": "https://api.github.com/repos/quarkusio/quarkus/labels/kind/bug",
      "name": "kind/bug",
      "color": "d73a4a",
      "default": false,
      "description": "Something isn't working"
    },
    {
      "id": 985346621,
      "node_id": "MDU6TGFiZWw5ODUzNDY2MjE=",
      "url": "https://api.github.com/repos/quarkusio/quarkus/labels/triage/duplicate",
      "name": "triage/duplicate",
      "color": "cfd3d7",
      "default": false,
      "description": "This issue or pull request already exists"
    },
    {
      "id": 2955097667,
      "node_id": "MDU6TGFiZWwyOTU1MDk3NjY3",
      "url": "https://api.github.com/repos/quarkusio/quarkus/labels/area/devservices",
      "name": "area/devservices",
      "color": "0366d6",
      "default": false,
      "description": ""
    }
  ],
  "state": "closed",
  "locked": false,
  "milestone": null,
  "comments": 6,
  "created_at": "2021-09-16T09:32:49Z",
  "updated_at": "2021-09-16T19:23:38Z",
  "closed_at": "2021-09-16T19:23:37Z",
  "active_lock_reason": null,
  "body": "### Describe the bug\n\nWhen the Quarkus application is restarted in the dev-mode and a dev-service also needs to be restarted, the application can after the restart no longer access the newly started dev-service.\r\n\r\nI debugged this in the case of a PostgreSQL database, where I explicitly set the property `quarkus.datasource.devservices.image-name` in `application.properties` to cause the dev-service to be force-restarted (which in itself may be a separate bug). The Docker container is properly restarted (listening on a new port) and the new configuration is correctly exposed using `RunTimeConfigurationDefaultBuildItem` instances. But when the application is restarted and ends up in `io.quarkus.deployment.steps.ConfigGenerationBuildStep#generateConfigClass()` the method immediately returns as `liveReloadBuildItem.isLiveReload()` evaluates to `true`. Consequently the `RunTimeConfigurationDefaultBuildItem` instances have no effect and the Quarkus application attempts to access the database using the old port rather than the new port.\n\n### Expected behavior\n\nThe Quarkus application should after a restart in dev-mode be able to access any restarted dev-services.\n\n### Actual behavior\n\nThe dev-services get restarted and will typically be listening on new ports, but the restarted Quarkus application will try to access the dev-service on the ports it used before the restart, which then fails.\r\n\r\n```\r\n11:19:36.278 ERROR [io.qu.de.de.IsolatedDevModeMain] (Aesh InputStream Reader) Failed to start quarkus: java.lang.RuntimeException: java.lang.RuntimeException: Failed to start quarkus\r\n        at io.quarkus.dev.appstate.ApplicationStateNotification.waitForApplicationStart(ApplicationStateNotification.java:51)\r\n        at io.quarkus.runner.bootstrap.StartupActionImpl.runMainClass(StartupActionImpl.java:109)\r\n        at io.quarkus.deployment.dev.IsolatedDevModeMain.restartApp(IsolatedDevModeMain.java:227)\r\n        at io.quarkus.deployment.dev.IsolatedDevModeMain.restartCallback(IsolatedDevModeMain.java:208)\r\n        at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:499)\r\n        at io.quarkus.deployment.console.ConsoleStateManager.forceRestart(ConsoleStateManager.java:136)\r\n        at io.quarkus.deployment.console.ConsoleStateManager.lambda$installBuiltins$0(ConsoleStateManager.java:98)\r\n        at io.quarkus.deployment.console.ConsoleStateManager$1.accept(ConsoleStateManager.java:73)\r\n        at io.quarkus.deployment.console.ConsoleStateManager$1.accept(ConsoleStateManager.java:46)\r\n        at io.quarkus.deployment.console.AeshConsole.lambda$setup$1(AeshConsole.java:199)\r\n        at org.aesh.terminal.EventDecoder.accept(EventDecoder.java:118)\r\n        at org.aesh.terminal.EventDecoder.accept(EventDecoder.java:31)\r\n        at org.aesh.terminal.io.Decoder.write(Decoder.java:133)\r\n        at org.aesh.readline.tty.terminal.TerminalConnection.openBlocking(TerminalConnection.java:216)\r\n        at org.aesh.readline.tty.terminal.TerminalConnection.openBlocking(TerminalConnection.java:203)\r\n        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\r\n        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\r\n        at java.base/java.lang.Thread.run(Thread.java:834)\r\nCaused by: java.lang.RuntimeException: Failed to start quarkus\r\n        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:1377)\r\n        at io.quarkus.runtime.Application.start(Application.java:101)\r\n        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:101)\r\n        at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)\r\n        at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)\r\n        at io.quarkus.runtime.Quarkus.run(Quarkus.java:119)\r\n        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)\r\n        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\r\n        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n        at java.base/java.lang.reflect.Method.invoke(Method.java:566)\r\n        at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:98)\r\n        ... 1 more\r\nCaused by: org.flywaydb.core.internal.exception.FlywaySqlException: Unable to obtain connection from database: Connection to localhost:49248 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.\r\n---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------\r\nSQL State  : 08001\r\nError Code : 0\r\nMessage    : Connection to localhost:49248 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.\r\n\r\n        at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:66)\r\n        at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:68)\r\n        at org.flywaydb.core.Flyway.execute(Flyway.java:502)\r\n        at org.flywaydb.core.Flyway.migrate(Flyway.java:168)\r\n        at io.quarkus.flyway.runtime.FlywayRecorder.doStartActions(FlywayRecorder.java:75)\r\n        at io.quarkus.deployment.steps.FlywayProcessor$createBeansAndStartActions-1520831253.deploy_0(FlywayProcessor$createBeansAndStartActions-1520831253.zig:84)\r\n        at io.quarkus.deployment.steps.FlywayProcessor$createBeansAndStartActions-1520831253.deploy(FlywayProcessor$createBeansAndStartActions-1520831253.zig:40)\r\n        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:1086)\r\n        ... 12 more\r\nCaused by: org.postgresql.util.PSQLException: Connection to localhost:49248 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.\r\n        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:303)\r\n        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:51)\r\n        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:223)\r\n        at org.postgresql.Driver.makeConnection(Driver.java:465)\r\n        at org.postgresql.Driver.connect(Driver.java:264)\r\n        at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:204)\r\n        at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:470)\r\n        at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:452)\r\n        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)\r\n        at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:68)\r\n        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1126)\r\n        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\r\n        ... 1 more\r\nCaused by: java.net.ConnectException: Connection refused: connect\r\n        at java.base/java.net.PlainSocketImpl.waitForConnect(Native Method)\r\n        at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:107)\r\n        at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)\r\n        at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)\r\n        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)\r\n        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)\r\n        at java.base/java.net.Socket.connect(Socket.java:609)\r\n        at org.postgresql.core.PGStream.createSocket(PGStream.java:231)\r\n        at org.postgresql.core.PGStream.<init>(PGStream.java:95)\r\n        at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:98)\r\n        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:213)\r\n        ... 12 more\r\n```\n\n### How to Reproduce?\n\n1. Create a Quarkus application with a PostgreSQL database and a simple Flyway migration script\r\n2. Set `quarkus.datasource.devservices.image-name=postgres:13` and `quarkus.flyway.migrate-at-start=true` in `application.properties`\r\n3. Start the application in dev-mod\r\n4. Force-restart the application using the keyboard shortcut `s`\r\n5. Now an exception should be visible in the console\n\n### Output of `uname -a` or `ver`\n\nMSYS_NT-10.0-22000 WIN10-KNUT 3.1.7-340.x86_64 2020-10-23 13:08 UTC x86_64 Msys\n\n### Output of `java -version`\n\nopenjdk version \"11.0.9\" 2020-10-20 LTS OpenJDK Runtime Environment Zulu11.43+22-SA (build 11.0.9+11-LTS) OpenJDK 64-Bit Server VM Zulu11.43+22-SA (build 11.0.9+11-LTS, mixed mode)\n\n### GraalVM version (if different from Java)\n\n_No response_\n\n### Quarkus version or git rev\n\n2.2.2.Final\n\n### Build tool (ie. output of `mvnw --version` or `gradlew --version`)\n\nMaven 3.8.1\n\n### Additional information\n\n_No response_",
  "reactions": {
    "url": "https://api.github.com/repos/quarkusio/quarkus/issues/20197/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/quarkusio/quarkus/issues/20197/timeline",
  "performed_via_github_app": null,
  "state_reason": "completed"
}
