{
  "url": "https://api.github.com/repos/quarkusio/quarkus/issues/20264",
  "repository_url": "https://api.github.com/repos/quarkusio/quarkus",
  "labels_url": "https://api.github.com/repos/quarkusio/quarkus/issues/20264/labels{/name}",
  "comments_url": "https://api.github.com/repos/quarkusio/quarkus/issues/20264/comments",
  "events_url": "https://api.github.com/repos/quarkusio/quarkus/issues/20264/events",
  "html_url": "https://github.com/quarkusio/quarkus/issues/20264",
  "id": 1000652031,
  "node_id": "I_kwDOCFbutM47pLz_",
  "number": 20264,
  "title": "Hibernate generates wrong SQL",
  "labels": [
    {
      "id": 985346620,
      "node_id": "MDU6TGFiZWw5ODUzNDY2MjA=",
      "url": "https://api.github.com/repos/quarkusio/quarkus/labels/kind/bug",
      "name": "kind/bug",
      "color": "d73a4a",
      "default": false,
      "description": "Something isn't working"
    },
    {
      "id": 1273026509,
      "node_id": "MDU6TGFiZWwxMjczMDI2NTA5",
      "url": "https://api.github.com/repos/quarkusio/quarkus/labels/area/persistence",
      "name": "area/persistence",
      "color": "FBCA04",
      "default": false,
      "description": "OBSOLETE, DO NOT USE"
    },
    {
      "id": 1425555736,
      "node_id": "MDU6TGFiZWwxNDI1NTU1NzM2",
      "url": "https://api.github.com/repos/quarkusio/quarkus/labels/area/hibernate-orm",
      "name": "area/hibernate-orm",
      "color": "0366d6",
      "default": false,
      "description": "Hibernate ORM"
    }
  ],
  "state": "closed",
  "locked": false,
  "milestone": null,
  "comments": 8,
  "created_at": "2021-09-20T07:25:07Z",
  "updated_at": "2021-09-22T04:19:42Z",
  "closed_at": "2021-09-21T10:20:39Z",
  "active_lock_reason": null,
  "body": "### Describe the bug\r\n\r\nThe update SQL Hibernate generated was wrong which caused exception.\r\n\r\nHQL:\r\n`update Document d set d.processed=false, d.error=false where d.documentGroup.domain=:domain and d.documentTypeDefinition=:documentTypeDefinition`\r\n\r\nSQL:\r\n`update\r\n        recognition_document cross \r\n    join\r\n    set\r\n        processed=false,\r\n        error=false \r\n    where\r\n        domain=? \r\n        and document_type=?`\r\n\r\n\r\n### Expected behavior\r\n\r\n`update recognition_document set processed=false, error=false where domain=? and document_type=?`\r\n\r\n### Actual behavior\r\n\r\nCaused by: org.postgresql.util.PSQLException: ERROR: syntax error at or near \"cross\"\r\n\r\n### How to Reproduce?\r\n\r\nHere is the reproducer (Docker is required to run the test case).\r\nhttps://github.com/jw941/hibernate-bug\r\n\r\n### Output of `uname -a` or `ver`\r\n\r\n_No response_\r\n\r\n### Output of `java -version`\r\n\r\n_No response_\r\n\r\n### GraalVM version (if different from Java)\r\n\r\n_No response_\r\n\r\n### Quarkus version or git rev\r\n\r\n2.2.3.Final\r\n\r\n### Build tool (ie. output of `mvnw --version` or `gradlew --version`)\r\n\r\n_No response_\r\n\r\n### Additional information\r\n\r\n_No response_",
  "reactions": {
    "url": "https://api.github.com/repos/quarkusio/quarkus/issues/20264/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/quarkusio/quarkus/issues/20264/timeline",
  "performed_via_github_app": null,
  "state_reason": "completed"
}
