{
  "url": "https://api.github.com/repos/quarkusio/quarkus/issues/20567",
  "repository_url": "https://api.github.com/repos/quarkusio/quarkus",
  "labels_url": "https://api.github.com/repos/quarkusio/quarkus/issues/20567/labels{/name}",
  "comments_url": "https://api.github.com/repos/quarkusio/quarkus/issues/20567/comments",
  "events_url": "https://api.github.com/repos/quarkusio/quarkus/issues/20567/events",
  "html_url": "https://github.com/quarkusio/quarkus/issues/20567",
  "id": 1018458973,
  "node_id": "I_kwDOCFbutM48tHNd",
  "number": 20567,
  "title": "Qute does not tell me which file has an error",
  "labels": [
    {
      "id": 985346620,
      "node_id": "MDU6TGFiZWw5ODUzNDY2MjA=",
      "url": "https://api.github.com/repos/quarkusio/quarkus/labels/kind/bug",
      "name": "kind/bug",
      "color": "d73a4a",
      "default": false,
      "description": "Something isn't working"
    },
    {
      "id": 1714005220,
      "node_id": "MDU6TGFiZWwxNzE0MDA1MjIw",
      "url": "https://api.github.com/repos/quarkusio/quarkus/labels/area/qute",
      "name": "area/qute",
      "color": "0366d6",
      "default": false,
      "description": "The template engine"
    }
  ],
  "state": "closed",
  "locked": false,
  "milestone": {
    "url": "https://api.github.com/repos/quarkusio/quarkus/milestones/150",
    "html_url": "https://github.com/quarkusio/quarkus/milestone/150",
    "labels_url": "https://api.github.com/repos/quarkusio/quarkus/milestones/150/labels",
    "id": 7178092,
    "node_id": "MI_kwDOCFbutM4AbYds",
    "number": 150,
    "title": "2.4.0.CR1",
    "description": "",
    "creator": {
      "login": "geoand",
      "id": 4374975,
      "node_id": "MDQ6VXNlcjQzNzQ5NzU=",
      "avatar_url": "https://avatars.githubusercontent.com/u/4374975?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/geoand",
      "html_url": "https://github.com/geoand",
      "followers_url": "https://api.github.com/users/geoand/followers",
      "following_url": "https://api.github.com/users/geoand/following{/other_user}",
      "gists_url": "https://api.github.com/users/geoand/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/geoand/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/geoand/subscriptions",
      "organizations_url": "https://api.github.com/users/geoand/orgs",
      "repos_url": "https://api.github.com/users/geoand/repos",
      "events_url": "https://api.github.com/users/geoand/events{/privacy}",
      "received_events_url": "https://api.github.com/users/geoand/received_events",
      "type": "User",
      "site_admin": false
    },
    "open_issues": 0,
    "closed_issues": 126,
    "state": "closed",
    "created_at": "2021-09-22T10:44:58Z",
    "updated_at": "2021-12-27T12:49:40Z",
    "due_on": "2021-10-11T07:00:00Z",
    "closed_at": "2021-10-15T08:11:06Z"
  },
  "comments": 3,
  "created_at": "2021-10-06T14:33:42Z",
  "updated_at": "2021-10-08T06:50:15Z",
  "closed_at": "2021-10-08T06:50:12Z",
  "active_lock_reason": null,
  "body": "### Describe the bug\n\nI'm porting some templates from a Play 1 app to Quarkus/Qute and I get the following exception:\r\n\r\n```\r\n2021-10-06 16:10:49,740 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (vert.x-worker-thread-0) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors\r\n\t[error]: Build step io.quarkus.qute.deployment.QuteProcessor#analyzeTemplates threw an exception: java.lang.IllegalArgumentException: Not a virtual method: )(/\r\n\tat io.quarkus.qute.Expressions.parseVirtualMethodParams(Expressions.java:39)\r\n\tat io.quarkus.qute.Parser.createPart(Parser.java:761)\r\n\tat io.quarkus.qute.Parser.parseExpression(Parser.java:743)\r\n\tat io.quarkus.qute.Parser.createPart(Parser.java:764)\r\n\tat io.quarkus.qute.Parser.parseExpression(Parser.java:743)\r\n\tat io.quarkus.qute.Parser.apply(Parser.java:817)\r\n\tat io.quarkus.qute.Parser.flushTag(Parser.java:486)\r\n\tat io.quarkus.qute.Parser.tag(Parser.java:293)\r\n\tat io.quarkus.qute.Parser.processCharacter(Parser.java:200)\r\n\tat io.quarkus.qute.Parser.parse(Parser.java:132)\r\n\tat io.quarkus.qute.EngineImpl.load(EngineImpl.java:138)\r\n```\r\n\r\nAnd it doesn't tell me which file it is, and I have dozens of them, so no idea where the error is :(\r\n\r\nCan we make sure we always display the error location?\n\n### Expected behavior\n\n_No response_\n\n### Actual behavior\n\n_No response_\n\n### How to Reproduce?\n\n_No response_\n\n### Output of `uname -a` or `ver`\n\n_No response_\n\n### Output of `java -version`\n\n_No response_\n\n### GraalVM version (if different from Java)\n\n_No response_\n\n### Quarkus version or git rev\n\n2.3.0.Final\n\n### Build tool (ie. output of `mvnw --version` or `gradlew --version`)\n\n_No response_\n\n### Additional information\n\n_No response_",
  "reactions": {
    "url": "https://api.github.com/repos/quarkusio/quarkus/issues/20567/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/quarkusio/quarkus/issues/20567/timeline",
  "performed_via_github_app": null,
  "state_reason": "completed"
}
