{
  "url": "https://api.github.com/repos/quarkusio/quarkus/issues/21935",
  "repository_url": "https://api.github.com/repos/quarkusio/quarkus",
  "labels_url": "https://api.github.com/repos/quarkusio/quarkus/issues/21935/labels{/name}",
  "comments_url": "https://api.github.com/repos/quarkusio/quarkus/issues/21935/comments",
  "events_url": "https://api.github.com/repos/quarkusio/quarkus/issues/21935/events",
  "html_url": "https://github.com/quarkusio/quarkus/issues/21935",
  "id": 1071525988,
  "node_id": "I_kwDOCFbutM4_3jBk",
  "number": 21935,
  "title": "Keycloak DevService not considered healthy when running in docker shared network mode",
  "labels": [
    {
      "id": 985346620,
      "node_id": "MDU6TGFiZWw5ODUzNDY2MjA=",
      "url": "https://api.github.com/repos/quarkusio/quarkus/labels/kind/bug",
      "name": "kind/bug",
      "color": "d73a4a",
      "default": false,
      "description": "Something isn't working"
    },
    {
      "id": 1375177076,
      "node_id": "MDU6TGFiZWwxMzc1MTc3MDc2",
      "url": "https://api.github.com/repos/quarkusio/quarkus/labels/area/testing",
      "name": "area/testing",
      "color": "0366d6",
      "default": false,
      "description": ""
    },
    {
      "id": 3289887215,
      "node_id": "MDU6TGFiZWwzMjg5ODg3MjE1",
      "url": "https://api.github.com/repos/quarkusio/quarkus/labels/area/keycloak",
      "name": "area/keycloak",
      "color": "0366d6",
      "default": false,
      "description": null
    }
  ],
  "state": "closed",
  "locked": false,
  "milestone": {
    "url": "https://api.github.com/repos/quarkusio/quarkus/milestones/158",
    "html_url": "https://github.com/quarkusio/quarkus/milestone/158",
    "labels_url": "https://api.github.com/repos/quarkusio/quarkus/milestones/158/labels",
    "id": 7346869,
    "node_id": "MI_kwDOCFbutM4AcBq1",
    "number": 158,
    "title": "2.6.0.CR1",
    "description": "",
    "creator": {
      "login": "gsmet",
      "id": 1279749,
      "node_id": "MDQ6VXNlcjEyNzk3NDk=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1279749?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/gsmet",
      "html_url": "https://github.com/gsmet",
      "followers_url": "https://api.github.com/users/gsmet/followers",
      "following_url": "https://api.github.com/users/gsmet/following{/other_user}",
      "gists_url": "https://api.github.com/users/gsmet/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/gsmet/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/gsmet/subscriptions",
      "organizations_url": "https://api.github.com/users/gsmet/orgs",
      "repos_url": "https://api.github.com/users/gsmet/repos",
      "events_url": "https://api.github.com/users/gsmet/events{/privacy}",
      "received_events_url": "https://api.github.com/users/gsmet/received_events",
      "type": "User",
      "site_admin": false
    },
    "open_issues": 0,
    "closed_issues": 238,
    "state": "closed",
    "created_at": "2021-11-10T17:24:12Z",
    "updated_at": "2022-01-01T18:29:17Z",
    "due_on": null,
    "closed_at": "2021-12-08T10:39:04Z"
  },
  "comments": 13,
  "created_at": "2021-12-05T18:30:15Z",
  "updated_at": "2021-12-08T07:35:31Z",
  "closed_at": "2021-12-08T07:35:28Z",
  "active_lock_reason": null,
  "body": "### Describe the bug\n\nWhen running the QuarkusIntegrationTest against the keycloak dev service using docker network (e.g. by setting `quarkus.container-image.build=true`) the http based health check fails:\r\n```\r\n2021-12-05 19:07:47,923 ERROR [üê≥ .io/.0.2]] (build-7) Could not start container: java.lang.IllegalArgumentException: Requested port (8080) is not mapped\r\n\tat org.testcontainers.containers.ContainerState.getMappedPort(ContainerState.java:153)\r\n\tat java.base/java.util.Optional.map(Optional.java:265)\r\n\tat org.testcontainers.containers.wait.strategy.HttpWaitStrategy.waitUntilReady(HttpWaitStrategy.java:177)\r\n\tat org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:51)\r\n\tat org.testcontainers.containers.GenericContainer.waitUntilContainerStarted(GenericContainer.java:929)\r\n\tat org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:468)\r\n\tat org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:331)\r\n\tat org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)\r\n\tat org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:329)\r\n\tat org.testcontainers.containers.GenericContainer.start(GenericContainer.java:317)\r\n\tat io.quarkus.oidc.deployment.devservices.keycloak.KeycloakDevServicesProcessor.lambda$startContainer$0(KeycloakDevServicesProcessor.java:303)\r\n```\r\n\r\nI tried a quick fix by adding:\r\n```java\r\n@Override\r\npublic Integer getMappedPort(int originalPort) {\r\n    if (useSharedNetwork) {                      \r\n        return KEYCLOAK_PORT;\r\n    } else {\r\n        return super.getMappedPort(originalPort);\r\n    }\r\n}\r\n```\r\n\r\nnear https://github.com/quarkusio/quarkus/blob/main/extensions/oidc/deployment/src/main/java/io/quarkus/oidc/deployment/devservices/keycloak/KeycloakDevServicesProcessor.java#L489\r\n\r\nThis solves the above exception, but it reveals another issue: The health check still fails because it tries to reach the `/auth` url on the internal network address (e.g. http://keycloak-8yVNc:8080/auth):\r\n```\r\nCaused by: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for URL to be accessible (http://keycloak-8yVNc:8080/auth should return HTTP 200)\r\n\tat org.testcontainers.containers.wait.strategy.HttpWaitStrategy.waitUntilReady(HttpWaitStrategy.java:264)\r\n```\r\n\r\nThis seems logical, since the healthcheck is made from outside the docker network. I also checked how other devservices are doing this, but none is using the HttpWaitStrategy.\n\n### Expected behavior\n\nKeycloak DevService gets recognized as healthy and the test can continue\n\n### Actual behavior\n\nException, see above\n\n### How to Reproduce?\n\nhttps://github.com/flo-02-mu/security-openid-connect-quickstart-networkerror\r\n\r\n1. `mvn verify`\n\n### Output of `uname -a` or `ver`\n\n20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64 x86_64\n\n### Output of `java -version`\n\nopenjdk 12.0.2 2019-07-16 OpenJDK Runtime Environment (build 12.0.2+10) OpenJDK 64-Bit Server VM (build 12.0.2+10, mixed mode, sharing)\n\n### GraalVM version (if different from Java)\n\n_No response_\n\n### Quarkus version or git rev\n\n2.5.1.Final (also tried on latest master)\n\n### Build tool (ie. output of `mvnw --version` or `gradlew --version`)\n\nApache Maven 3.6.2 (40f52333136460af0dc0d7232c0dc0bcf0d9e117; 2019-08-27T17:06:16+02:00)\n\n### Additional information\n\n_No response_",
  "reactions": {
    "url": "https://api.github.com/repos/quarkusio/quarkus/issues/21935/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/quarkusio/quarkus/issues/21935/timeline",
  "performed_via_github_app": null,
  "state_reason": "completed"
}
