{
  "url": "https://api.github.com/repos/quarkusio/quarkus/issues/24247",
  "repository_url": "https://api.github.com/repos/quarkusio/quarkus",
  "labels_url": "https://api.github.com/repos/quarkusio/quarkus/issues/24247/labels{/name}",
  "comments_url": "https://api.github.com/repos/quarkusio/quarkus/issues/24247/comments",
  "events_url": "https://api.github.com/repos/quarkusio/quarkus/issues/24247/events",
  "html_url": "https://github.com/quarkusio/quarkus/issues/24247",
  "id": 1165497732,
  "node_id": "I_kwDOCFbutM5FeBWE",
  "number": 24247,
  "title": "org.hibernate.validator.PredefinedScopeHibernateValidator can not be instantiated reflectively",
  "labels": [
    {
      "id": 985346625,
      "node_id": "MDU6TGFiZWw5ODUzNDY2MjU=",
      "url": "https://api.github.com/repos/quarkusio/quarkus/labels/triage/invalid",
      "name": "triage/invalid",
      "color": "e4e669",
      "default": false,
      "description": "This doesn't seem right"
    },
    {
      "id": 985346626,
      "node_id": "MDU6TGFiZWw5ODUzNDY2MjY=",
      "url": "https://api.github.com/repos/quarkusio/quarkus/labels/kind/question",
      "name": "kind/question",
      "color": "d876e3",
      "default": false,
      "description": "Further information is requested"
    },
    {
      "id": 1305687763,
      "node_id": "MDU6TGFiZWwxMzA1Njg3NzYz",
      "url": "https://api.github.com/repos/quarkusio/quarkus/labels/area/hibernate-validator",
      "name": "area/hibernate-validator",
      "color": "0366d6",
      "default": false,
      "description": "Hibernate Validator"
    },
    {
      "id": 2744442223,
      "node_id": "MDU6TGFiZWwyNzQ0NDQyMjIz",
      "url": "https://api.github.com/repos/quarkusio/quarkus/labels/triage/needs-reproducer",
      "name": "triage/needs-reproducer",
      "color": "FDE078",
      "default": false,
      "description": "We are waiting for a reproducer."
    }
  ],
  "state": "closed",
  "locked": false,
  "milestone": null,
  "comments": 8,
  "created_at": "2022-03-10T17:11:50Z",
  "updated_at": "2022-10-14T15:18:58Z",
  "closed_at": "2022-10-14T15:18:52Z",
  "active_lock_reason": null,
  "body": "### Describe the bug\r\n\r\nI'm trying to get my natively compiled application running, but I'm getting problems because of Hibernate Validator:\r\n\r\n```\r\nException in thread \"main\" java.lang.ExceptionInInitializerError\r\n        at java.lang.Class.ensureInitialized(DynamicHub.java:510)\r\n        at java.lang.Class.newInstance(DynamicHub.java:874)\r\n        at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)\r\n        at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)\r\n        at io.quarkus.runtime.Quarkus.run(Quarkus.java:120)\r\n        at io.quarkus.runner.GeneratedMain.main(Unknown Source)\r\nCaused by: java.lang.RuntimeException: Failed to start quarkus\r\n        at io.quarkus.runner.ApplicationImpl.<clinit>(Unknown Source)\r\n        ... 6 more\r\nCaused by: javax.validation.ValidationException: Cannot instantiate provider type: class org.hibernate.validator.PredefinedScopeHibernateValidator\r\n        at javax.validation.Validation$NewProviderInstance.run(Validation.java:422)\r\n        at javax.validation.Validation$NewProviderInstance.run(Validation.java:404)\r\n        at javax.validation.Validation$ProviderSpecificBootstrapImpl.run(Validation.java:240)\r\n        at javax.validation.Validation$ProviderSpecificBootstrapImpl.configure(Validation.java:213)\r\n        at io.quarkus.hibernate.validator.runtime.HibernateValidatorRecorder$2.created(HibernateValidatorRecorder.java:50)\r\n        at io.quarkus.arc.runtime.ArcRecorder.initBeanContainer(ArcRecorder.java:70)\r\n        at io.quarkus.deployment.steps.ArcProcessor$generateResources686947423.deploy_0(Unknown Source)\r\n        at io.quarkus.deployment.steps.ArcProcessor$generateResources686947423.deploy(Unknown Source)\r\n        ... 7 more\r\nCaused by: java.lang.InstantiationException: Type `org.hibernate.validator.PredefinedScopeHibernateValidator` can not be instantiated reflectively as it does not have a no-parameter constructor or the no-parameter constructor has not been added explicitly to the native image.\r\n        at java.lang.Class.newInstance(DynamicHub.java:881)\r\n        at javax.validation.Validation$NewProviderInstance.run(Validation.java:419)\r\n        ... 14 more\r\n```\r\n\r\nIs this \"normal\" or is Hibernate Validator supposed to be working out of the box natively?\r\n\r\nI've also tried `--initialize-at-run-time=org.hibernate.validator.PredefinedScopeHibernateValidator` without success.\r\n\r\n### Expected behavior\r\n\r\n_No response_\r\n\r\n### Actual behavior\r\n\r\n_No response_\r\n\r\n### How to Reproduce?\r\n\r\n_No response_\r\n\r\n### Output of `uname -a` or `ver`\r\n\r\n_No response_\r\n\r\n### Output of `java -version`\r\n\r\nopenjdk-17\r\n\r\n### GraalVM version (if different from Java)\r\n\r\nquay.io/quarkus/ubi-quarkus-native-image:22.0.0-java17\r\n\r\n### Quarkus version or git rev\r\n\r\n2.7.4\r\n\r\n### Build tool (ie. output of `mvnw --version` or `gradlew --version`)\r\n\r\n_No response_\r\n\r\n### Additional information\r\n\r\n_No response_",
  "reactions": {
    "url": "https://api.github.com/repos/quarkusio/quarkus/issues/24247/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/quarkusio/quarkus/issues/24247/timeline",
  "performed_via_github_app": null,
  "state_reason": "not_planned"
}
