{
  "url": "https://api.github.com/repos/quarkusio/quarkus/issues/28493",
  "repository_url": "https://api.github.com/repos/quarkusio/quarkus",
  "labels_url": "https://api.github.com/repos/quarkusio/quarkus/issues/28493/labels{/name}",
  "comments_url": "https://api.github.com/repos/quarkusio/quarkus/issues/28493/comments",
  "events_url": "https://api.github.com/repos/quarkusio/quarkus/issues/28493/events",
  "html_url": "https://github.com/quarkusio/quarkus/issues/28493",
  "id": 1403705154,
  "node_id": "I_kwDOCFbutM5TqtdC",
  "number": 28493,
  "title": "Funqy Knative Events breaks over multiple matching invokers when function name & trigger are combined",
  "labels": [
    {
      "id": 985346620,
      "node_id": "MDU6TGFiZWw5ODUzNDY2MjA=",
      "url": "https://api.github.com/repos/quarkusio/quarkus/labels/kind/bug",
      "name": "kind/bug",
      "color": "d73a4a",
      "default": false,
      "description": "Something isn't working"
    },
    {
      "id": 1654772125,
      "node_id": "MDU6TGFiZWwxNjU0NzcyMTI1",
      "url": "https://api.github.com/repos/quarkusio/quarkus/labels/area/kubernetes",
      "name": "area/kubernetes",
      "color": "0366d6",
      "default": false,
      "description": ""
    },
    {
      "id": 1958884827,
      "node_id": "MDU6TGFiZWwxOTU4ODg0ODI3",
      "url": "https://api.github.com/repos/quarkusio/quarkus/labels/area/funqy",
      "name": "area/funqy",
      "color": "0366d6",
      "default": false,
      "description": ""
    }
  ],
  "state": "closed",
  "locked": false,
  "milestone": {
    "url": "https://api.github.com/repos/quarkusio/quarkus/milestones/206",
    "html_url": "https://github.com/quarkusio/quarkus/milestone/206",
    "labels_url": "https://api.github.com/repos/quarkusio/quarkus/milestones/206/labels",
    "id": 8420367,
    "node_id": "MI_kwDOCFbutM4AgHwP",
    "number": 206,
    "title": "2.14.0.CR1",
    "description": "",
    "creator": {
      "login": "gsmet",
      "id": 1279749,
      "node_id": "MDQ6VXNlcjEyNzk3NDk=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1279749?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/gsmet",
      "html_url": "https://github.com/gsmet",
      "followers_url": "https://api.github.com/users/gsmet/followers",
      "following_url": "https://api.github.com/users/gsmet/following{/other_user}",
      "gists_url": "https://api.github.com/users/gsmet/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/gsmet/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/gsmet/subscriptions",
      "organizations_url": "https://api.github.com/users/gsmet/orgs",
      "repos_url": "https://api.github.com/users/gsmet/repos",
      "events_url": "https://api.github.com/users/gsmet/events{/privacy}",
      "received_events_url": "https://api.github.com/users/gsmet/received_events",
      "type": "User",
      "site_admin": false
    },
    "open_issues": 0,
    "closed_issues": 224,
    "state": "closed",
    "created_at": "2022-09-14T06:18:10Z",
    "updated_at": "2023-05-15T13:54:56Z",
    "due_on": null,
    "closed_at": "2022-10-26T12:52:36Z"
  },
  "comments": 1,
  "created_at": "2022-10-10T20:57:47Z",
  "updated_at": "2022-10-19T14:01:15Z",
  "closed_at": "2022-10-19T14:01:12Z",
  "active_lock_reason": null,
  "body": "### Describe the bug\r\n\r\nI can set trigger (cloud event filter that triggers Funqy Knative Events function) via `io.quarkus.funqy.knative.events.CloudEventMapping#trigger`, if I don't do that, function name is used as trigger. I defined additional attribute filter with `@EventAttribute`, used function name as `trigger` and received an exception. The documentation doesn't mention `@EventAttribute` single time (see https://github.com/quarkusio/quarkus/issues/28490), so I don't know what expected behavior is. https://github.com/quarkusio/quarkus/pull/17655 that added the attribute provides context on what author intention was, but doesn't explain why I can't use function name.\r\n\r\n### Expected behavior\r\n\r\nException is not thrown, filter is applied. Or documentation correct my expectations (please kindly explain reasons for such behavior).\r\n\r\n\r\n### Actual behavior\r\n\r\nAn exception is thrown\r\n```bash\r\n...\r\nCaused by: java.lang.IllegalStateException: Function for trigger 'bar' has multiple matching invokers\r\n...\r\n```\r\n\r\n### How to Reproduce?\r\n\r\nReproducer:\r\n\r\nSteps to reproduce the behavior:\r\n1. use `funqy-knative-events-quickstart`\r\n2. add functions below to `org.acme.funqy.SimpleFunctionChain`\r\n```Java\r\n    @Funq\r\n    @CloudEventMapping(attributes = {\r\n            @EventAttribute(name = \"custom\", value = \"bar\") })\r\n    public String bar(String input) {\r\n        return \"bar\";\r\n    }\r\n\r\n    @Funq\r\n    @CloudEventMapping(trigger = \"bar\", attributes = {\r\n            @EventAttribute(name = \"custom\", value = \"foo\") })\r\n    public String foo(String input) {\r\n        return \"foo\";\r\n    }\r\n```\r\n\r\nOn the other hand, if you set `trigger = \"bar\"` to `org.acme.funqy.SimpleFunctionChain#bar`, everything works as (I) expected.\r\n\r\n### Output of `uname -a` or `ver`\r\n\r\n_No response_\r\n\r\n### Output of `java -version`\r\n\r\n_No response_\r\n\r\n### GraalVM version (if different from Java)\r\n\r\n_No response_\r\n\r\n### Quarkus version or git rev\r\n\r\n_No response_\r\n\r\n### Build tool (ie. output of `mvnw --version` or `gradlew --version`)\r\n\r\n_No response_\r\n\r\n### Additional information\r\n\r\n_No response_",
  "reactions": {
    "url": "https://api.github.com/repos/quarkusio/quarkus/issues/28493/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/quarkusio/quarkus/issues/28493/timeline",
  "performed_via_github_app": null,
  "state_reason": "completed"
}
