{
  "url": "https://api.github.com/repos/quarkusio/quarkus/issues/30561",
  "repository_url": "https://api.github.com/repos/quarkusio/quarkus",
  "labels_url": "https://api.github.com/repos/quarkusio/quarkus/issues/30561/labels{/name}",
  "comments_url": "https://api.github.com/repos/quarkusio/quarkus/issues/30561/comments",
  "events_url": "https://api.github.com/repos/quarkusio/quarkus/issues/30561/events",
  "html_url": "https://github.com/quarkusio/quarkus/issues/30561",
  "id": 1554034365,
  "node_id": "I_kwDOCFbutM5coK69",
  "number": 30561,
  "title": "Log exception caught by GrpcDuplicatedContextGrpcInterceptor.ListenedOnDuplicatedContext#invoke",
  "labels": [
    {
      "id": 985346620,
      "node_id": "MDU6TGFiZWw5ODUzNDY2MjA=",
      "url": "https://api.github.com/repos/quarkusio/quarkus/labels/kind/bug",
      "name": "kind/bug",
      "color": "d73a4a",
      "default": false,
      "description": "Something isn't working"
    },
    {
      "id": 2062531368,
      "node_id": "MDU6TGFiZWwyMDYyNTMxMzY4",
      "url": "https://api.github.com/repos/quarkusio/quarkus/labels/area/grpc",
      "name": "area/grpc",
      "color": "0366d6",
      "default": false,
      "description": "gRPC"
    }
  ],
  "state": "closed",
  "locked": false,
  "milestone": null,
  "comments": 4,
  "created_at": "2023-01-24T00:11:45Z",
  "updated_at": "2023-01-26T17:15:34Z",
  "closed_at": "2023-01-26T17:15:33Z",
  "active_lock_reason": null,
  "body": "### Describe the bug\n\nhttps://github.com/quarkusio/quarkus/pull/28063 added handling of uncaught exceptions from gRPC downstream interceptors, so now gRPC call is properly closed. This is good.\r\n\r\nBut now the exception is no longer logged. I had to spend quite a lot of time debugging to get to the real reason why gRPC call was closed by the server.\r\n\r\nCould you please log the exception, that triggered closing of gRPC call in GrpcDuplicatedContextGrpcInterceptor.ListenedOnDuplicatedContext#invoke?\r\n\n\n### Expected behavior\n\nException logged and gRPC call closed\n\n### Actual behavior\n\ngRPC call is closed silently, leaving no trace in the log\n\n### How to Reproduce?\n\n_No response_\n\n### Output of `uname -a` or `ver`\n\n_No response_\n\n### Output of `java -version`\n\n_No response_\n\n### GraalVM version (if different from Java)\n\n_No response_\n\n### Quarkus version or git rev\n\nQuarkus 2.13.6\n\n### Build tool (ie. output of `mvnw --version` or `gradlew --version`)\n\n_No response_\n\n### Additional information\n\n_No response_",
  "reactions": {
    "url": "https://api.github.com/repos/quarkusio/quarkus/issues/30561/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/quarkusio/quarkus/issues/30561/timeline",
  "performed_via_github_app": null,
  "state_reason": "completed"
}
