{
  "url": "https://api.github.com/repos/quarkusio/quarkus/issues/31808",
  "repository_url": "https://api.github.com/repos/quarkusio/quarkus",
  "labels_url": "https://api.github.com/repos/quarkusio/quarkus/issues/31808/labels{/name}",
  "comments_url": "https://api.github.com/repos/quarkusio/quarkus/issues/31808/comments",
  "events_url": "https://api.github.com/repos/quarkusio/quarkus/issues/31808/events",
  "html_url": "https://github.com/quarkusio/quarkus/issues/31808",
  "id": 1621280614,
  "node_id": "I_kwDOCFbutM5gosdm",
  "number": 31808,
  "title": "Unknown SEQUENCE: 'quarkus.hibernate_sequence'",
  "labels": [
    {
      "id": 985346620,
      "node_id": "MDU6TGFiZWw5ODUzNDY2MjA=",
      "url": "https://api.github.com/repos/quarkusio/quarkus/labels/kind/bug",
      "name": "kind/bug",
      "color": "d73a4a",
      "default": false,
      "description": "Something isn't working"
    },
    {
      "id": 1273026509,
      "node_id": "MDU6TGFiZWwxMjczMDI2NTA5",
      "url": "https://api.github.com/repos/quarkusio/quarkus/labels/area/persistence",
      "name": "area/persistence",
      "color": "FBCA04",
      "default": false,
      "description": "OBSOLETE, DO NOT USE"
    },
    {
      "id": 1425555736,
      "node_id": "MDU6TGFiZWwxNDI1NTU1NzM2",
      "url": "https://api.github.com/repos/quarkusio/quarkus/labels/area/hibernate-orm",
      "name": "area/hibernate-orm",
      "color": "0366d6",
      "default": false,
      "description": "Hibernate ORM"
    }
  ],
  "state": "closed",
  "locked": false,
  "milestone": null,
  "comments": 4,
  "created_at": "2023-03-13T11:16:37Z",
  "updated_at": "2023-03-13T13:12:26Z",
  "closed_at": "2023-03-13T11:42:53Z",
  "active_lock_reason": null,
  "body": "### Describe the bug\n\nUsing import.sql that references hibernate_sequence results in WARN message at the Dev mode startup:\r\n\r\n```\r\n2023-03-13 12:13:05,996 WARN  [org.mar.jdb.mes.ser.ErrorPacket] (JPA Startup Thread) Error: 4091-42S02: Unknown SEQUENCE: 'quarkus.hibernate_sequence'\r\n2023-03-13 12:13:05,997 WARN  [org.hib.too.sch.int.ExceptionHandlerLoggedImpl] (JPA Startup Thread) GenerationTarget encountered exception accepting command : Error executing DDL \"drop sequence hibernate_sequence\" via JDBC Statement: org.hibernate.tool.schema.spi.CommandAcceptanceException: Error executing DDL \"drop sequence hibernate_sequence\" via JDBC Statement\r\n\tat org.hibernate.tool.schema.internal.exec.GenerationTargetToDatabase.accept(GenerationTargetToDatabase.java:67)\r\n\tat org.hibernate.tool.schema.internal.SchemaDropperImpl.applySqlString(SchemaDropperImpl.java:387)\r\n\tat org.hibernate.tool.schema.internal.SchemaDropperImpl.applySqlStrings(SchemaDropperImpl.java:371)\r\n\tat org.hibernate.tool.schema.internal.SchemaDropperImpl.dropFromMetadata(SchemaDropperImpl.java:256)\r\n\tat org.hibernate.tool.schema.internal.SchemaDropperImpl.performDrop(SchemaDropperImpl.java:156)\r\n\tat org.hibernate.tool.schema.internal.SchemaDropperImpl.doDrop(SchemaDropperImpl.java:128)\r\n\tat org.hibernate.tool.schema.internal.SchemaDropperImpl.doDrop(SchemaDropperImpl.java:114)\r\n\tat org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.performDatabaseAction(SchemaManagementToolCoordinator.java:157)\r\n\tat org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.process(SchemaManagementToolCoordinator.java:85)\r\n\tat org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:335)\r\n\tat io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.build(FastBootEntityManagerFactoryBuilder.java:74)\r\n\tat io.quarkus.hibernate.orm.runtime.FastBootHibernatePersistenceProvider.createEntityManagerFactory(FastBootHibernatePersistenceProvider.java:72)\r\n\tat javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:80)\r\n\tat javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:55)\r\n\tat io.quarkus.hibernate.orm.runtime.JPAConfig$LazyPersistenceUnit.get(JPAConfig.java:167)\r\n\tat io.quarkus.hibernate.orm.runtime.JPAConfig$1.run(JPAConfig.java:68)\r\n\tat java.base/java.lang.Thread.run(Thread.java:833)\r\nCaused by: java.sql.SQLSyntaxErrorException: (conn=4) Unknown SEQUENCE: 'quarkus.hibernate_sequence'\r\n\tat org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:282)\r\n\tat org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)\r\n\tat org.mariadb.jdbc.message.ClientMessage.readPacket(ClientMessage.java:134)\r\n\tat org.mariadb.jdbc.client.impl.StandardClient.readPacket(StandardClient.java:855)\r\n\tat org.mariadb.jdbc.client.impl.StandardClient.readResults(StandardClient.java:794)\r\n\tat org.mariadb.jdbc.client.impl.StandardClient.readResponse(StandardClient.java:713)\r\n\tat org.mariadb.jdbc.client.impl.StandardClient.execute(StandardClient.java:637)\r\n\tat org.mariadb.jdbc.Statement.executeInternal(Statement.java:941)\r\n\tat org.mariadb.jdbc.Statement.execute(Statement.java:1067)\r\n\tat org.mariadb.jdbc.Statement.execute(Statement.java:458)\r\n\tat io.agroal.pool.wrapper.StatementWrapper.execute(StatementWrapper.java:235)\r\n\tat org.hibernate.tool.schema.internal.exec.GenerationTargetToDatabase.accept(GenerationTargetToDatabase.java:54)\r\n\t... 16 more\r\n```\r\n\r\nOnly a message, the sequence works in the import.sql script.\n\n### Expected behavior\n\nNo error if the hibernate_sequence is not found.\n\n### Actual behavior\n\nWARN messages are printed.\n\n### How to Reproduce?\n\nhttps://github.com/xstefank/quarkus-reproducers/tree/main/mysql-import-sql\r\n\r\n$ quarkus dev\n\n### Output of `uname -a` or `ver`\n\n_No response_\n\n### Output of `java -version`\n\n_No response_\n\n### GraalVM version (if different from Java)\n\n_No response_\n\n### Quarkus version or git rev\n\n_No response_\n\n### Build tool (ie. output of `mvnw --version` or `gradlew --version`)\n\n_No response_\n\n### Additional information\n\nIs it possible I have something wrong with import.sql? I think I read somewhere that something changed?",
  "reactions": {
    "url": "https://api.github.com/repos/quarkusio/quarkus/issues/31808/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/quarkusio/quarkus/issues/31808/timeline",
  "performed_via_github_app": null,
  "state_reason": "not_planned"
}
