{
  "url": "https://api.github.com/repos/quarkusio/quarkus/issues/35238",
  "repository_url": "https://api.github.com/repos/quarkusio/quarkus",
  "labels_url": "https://api.github.com/repos/quarkusio/quarkus/issues/35238/labels{/name}",
  "comments_url": "https://api.github.com/repos/quarkusio/quarkus/issues/35238/comments",
  "events_url": "https://api.github.com/repos/quarkusio/quarkus/issues/35238/events",
  "html_url": "https://github.com/quarkusio/quarkus/issues/35238",
  "id": 1839184670,
  "node_id": "I_kwDOCFbutM5tn7se",
  "number": 35238,
  "title": "Narayana automatic recovery of JDBC XA resources only works after datasources was initialized manually",
  "labels": [
    {
      "id": 985346620,
      "node_id": "MDU6TGFiZWw5ODUzNDY2MjA=",
      "url": "https://api.github.com/repos/quarkusio/quarkus/labels/kind/bug",
      "name": "kind/bug",
      "color": "d73a4a",
      "default": false,
      "description": "Something isn't working"
    },
    {
      "id": 1633508165,
      "node_id": "MDU6TGFiZWwxNjMzNTA4MTY1",
      "url": "https://api.github.com/repos/quarkusio/quarkus/labels/area/narayana",
      "name": "area/narayana",
      "color": "0366d6",
      "default": false,
      "description": "Transactions / Narayana"
    }
  ],
  "state": "closed",
  "locked": false,
  "milestone": {
    "url": "https://api.github.com/repos/quarkusio/quarkus/milestones/255",
    "html_url": "https://github.com/quarkusio/quarkus/milestone/255",
    "labels_url": "https://api.github.com/repos/quarkusio/quarkus/milestones/255/labels",
    "id": 9565017,
    "node_id": "MI_kwDOCFbutM4AkfNZ",
    "number": 255,
    "title": "3.3.0.CR1",
    "description": "",
    "creator": {
      "login": "gsmet",
      "id": 1279749,
      "node_id": "MDQ6VXNlcjEyNzk3NDk=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1279749?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/gsmet",
      "html_url": "https://github.com/gsmet",
      "followers_url": "https://api.github.com/users/gsmet/followers",
      "following_url": "https://api.github.com/users/gsmet/following{/other_user}",
      "gists_url": "https://api.github.com/users/gsmet/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/gsmet/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/gsmet/subscriptions",
      "organizations_url": "https://api.github.com/users/gsmet/orgs",
      "repos_url": "https://api.github.com/users/gsmet/repos",
      "events_url": "https://api.github.com/users/gsmet/events{/privacy}",
      "received_events_url": "https://api.github.com/users/gsmet/received_events",
      "type": "User",
      "site_admin": false
    },
    "open_issues": 0,
    "closed_issues": 310,
    "state": "closed",
    "created_at": "2023-06-21T07:35:19Z",
    "updated_at": "2024-05-17T05:53:43Z",
    "due_on": null,
    "closed_at": "2023-08-09T11:23:12Z"
  },
  "comments": 12,
  "created_at": "2023-08-07T10:44:02Z",
  "updated_at": "2023-08-09T06:27:50Z",
  "closed_at": "2023-08-09T06:27:45Z",
  "active_lock_reason": null,
  "body": "### Describe the bug\n\nIf I want periodic recovery module to recover my failed transaction stored in JDBC object store, I need first to have datasources initialized (e.g. when I sent request or with startevent I use datasources).\n\n### Expected behavior\n\nWhen app starts, failed transactions recover.\n\n### Actual behavior\n\nException and no recovery:\r\n\r\n```\r\n2023-08-06 23:56:26,715 WARN  [com.arj.ats.jta] (Periodic Recovery) ARJUNA016037: Could not find new XAResource to use for recovering non-serializable XAResource XAResourceRecord < resource:null, txid:< formatId=131077, gtrid_length=46, bqual_length=36, tx_uid=0:ffff0a0000b9:af1b:64d01657:11, node_name=quarkus-quickstart, branch_uid=0:ffff0a0000b9:af1b:64d01657:17, subordinatenodename=null, eis_name=0 >, heuristic: TwoPhaseOutcome.FINISH_OK com.arjuna.ats.internal.jta.resources.arjunacore.XAResourceRecord@55ea0fec >\r\n2023-08-06 23:56:26,719 WARN  [com.arj.ats.jta] (Periodic Recovery) ARJUNA016038: No XAResource to recover < formatId=131077, gtrid_length=46, bqual_length=36, tx_uid=0:ffff0a0000b9:af1b:64d01657:11, node_name=quarkus-quickstart, branch_uid=0:ffff0a0000b9:af1b:64d01657:13, subordinatenodename=null, eis_name=0 >\r\n```\r\n\r\nRecovery doesn't work till I use datasources myself. @zhfeng explained to me here https://github.com/quarkusio/quarkus-quickstarts/pull/1311#issuecomment-1667031126 that there was changes in Agroal regarding ds initialization https://github.com/quarkusio/quarkus/blob/main/extensions/agroal/runtime/src/main/java/io/quarkus/agroal/runtime/AgroalRecorder.java#L28-L30.\r\n\r\nI've tested Zheng suggestion with following code that did a trick (I do not propose use such thing! it's just for context):\r\nhttps://github.com/quarkusio/quarkus-quickstarts/pull/1311#issuecomment-1667606419\n\n### How to Reproduce?\n\nReproducer:\r\n\r\nfollow readme added here https://github.com/quarkusio/quarkus-quickstarts/pull/1311. There are steps that you need to follow, you will see that if you don't do `curl -v localhost:8080/transaction-logs/annotation-way`, transaction is never recovered and an exception is repeatedly logged.\n\n### Output of `uname -a` or `ver`\n\nFedora\n\n### Output of `java -version`\n\nOpenJDK Runtime Environment Temurin-17.0.7+7\n\n### GraalVM version (if different from Java)\n\n22.3\n\n### Quarkus version or git rev\n\n999-SNAPSHOT\n\n### Build tool (ie. output of `mvnw --version` or `gradlew --version`)\n\nApache Maven 3.9.3\n\n### Additional information\n\nRelated to https://github.com/quarkusio/quarkus/pull/34545 ? Didn't check (on PTO).",
  "reactions": {
    "url": "https://api.github.com/repos/quarkusio/quarkus/issues/35238/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/quarkusio/quarkus/issues/35238/timeline",
  "performed_via_github_app": null,
  "state_reason": "completed"
}
