{
  "url": "https://api.github.com/repos/quarkusio/quarkus/issues/36784",
  "repository_url": "https://api.github.com/repos/quarkusio/quarkus",
  "labels_url": "https://api.github.com/repos/quarkusio/quarkus/issues/36784/labels{/name}",
  "comments_url": "https://api.github.com/repos/quarkusio/quarkus/issues/36784/comments",
  "events_url": "https://api.github.com/repos/quarkusio/quarkus/issues/36784/events",
  "html_url": "https://github.com/quarkusio/quarkus/issues/36784",
  "id": 1968657655,
  "node_id": "I_kwDOCFbutM51V1T3",
  "number": 36784,
  "title": "Quickstart broken",
  "labels": [],
  "state": "closed",
  "locked": false,
  "milestone": null,
  "comments": 0,
  "created_at": "2023-10-30T15:33:09Z",
  "updated_at": "2023-10-30T16:23:32Z",
  "closed_at": "2023-10-30T16:23:30Z",
  "active_lock_reason": null,
  "body": "I tried to quickstart this project: https://github.com/quarkusio/quarkus-quickstarts/tree/main/security-keycloak-authorization-quickstart \r\nBut it always gives an error that the backend service is not a valid real. \r\nIs it possible to update both the documentation and the quickstart?\r\n\r\nThe log: \r\n`2023-10-30 16:30:08,073 ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application (with profile [dev]): java.lang.RuntimeException: Failed to start quarkus\r\n        at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)\r\n        at io.quarkus.runtime.Application.start(Application.java:101)\r\n        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)\r\n        at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)\r\n        at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)\r\n        at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)\r\n        at io.quarkus.runner.GeneratedMain.main(Unknown Source)\r\n        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\r\n        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n        at java.base/java.lang.reflect.Method.invoke(Method.java:568)\r\n        at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:104)\r\n        at java.base/java.lang.Thread.run(Thread.java:833)\r\nCaused by: java.lang.RuntimeException: Could not find resource\r\n        at org.keycloak.authorization.client.util.Throwables.handleWrapException(Throwables.java:45)\r\n        at org.keycloak.authorization.client.resource.ProtectedResource.findAll(ProtectedResource.java:249)\r\n        at org.keycloak.adapters.authorization.PathConfigMatcher.configureAllPathsForResourceServer(PathConfigMatcher.java:280)\r\n        at org.keycloak.adapters.authorization.PathConfigMatcher.configurePaths(PathConfigMatcher.java:204)\r\n        at org.keycloak.adapters.authorization.PathConfigMatcher.<init>(PathConfigMatcher.java:57)\r\n        at org.keycloak.adapters.authorization.PolicyEnforcer.<init>(PolicyEnforcer.java:105)\r\n        at org.keycloak.adapters.authorization.PolicyEnforcer$Builder.build(PolicyEnforcer.java:662)\r\n        at io.quarkus.keycloak.pep.runtime.KeycloakPolicyEnforcerRecorder.createPolicyEnforcer(KeycloakPolicyEnforcerRecorder.java:113)\r\n        at io.quarkus.keycloak.pep.runtime.KeycloakPolicyEnforcerRecorder.setup(KeycloakPolicyEnforcerRecorder.java:37)\r\n        at io.quarkus.deployment.steps.KeycloakPolicyEnforcerBuildStep$setup1036344509.deploy_0(Unknown Source)\r\n        at io.quarkus.deployment.steps.KeycloakPolicyEnforcerBuildStep$setup1036344509.deploy(Unknown Source)\r\n        ... 13 more\r\nCaused by: org.keycloak.authorization.client.AuthorizationDeniedException: org.keycloak.authorization.client.util.HttpResponseException: Unexpected response from server: 403 / Forbidden / Response from server: {\"error\":\"invalid_clientId\",\"error_description\":\"Client application [backend-service] is not registered as a resource server.\"}\r\n        at org.keycloak.authorization.client.util.Throwables.handleAndWrapHttpResponseException(Throwables.java:96)\r\n        at org.keycloak.authorization.client.util.Throwables.handleWrapException(Throwables.java:42)\r\n        at org.keycloak.authorization.client.util.Throwables.retryAndWrapExceptionIfNecessary(Throwables.java:87)\r\n        at org.keycloak.authorization.client.resource.ProtectedResource.find(ProtectedResource.java:182)\r\n        at org.keycloak.authorization.client.resource.ProtectedResource.findAll(ProtectedResource.java:247)\r\n        ... 22 more\r\nCaused by: org.keycloak.authorization.client.util.HttpResponseException: Unexpected response from server: 403 / Forbidden / Response from server: {\"error\":\"invalid_clientId\",\"error_description\":\"Client application [backend-service] is not registered as a resource server.\"}\r\n        at org.keycloak.authorization.client.util.HttpMethod.execute(HttpMethod.java:103)\r\n        at org.keycloak.authorization.client.util.HttpMethodResponse$2.execute(HttpMethodResponse.java:50)\r\n        at org.keycloak.authorization.client.resource.ProtectedResource$4.call(ProtectedResource.java:176)\r\n        at org.keycloak.authorization.client.resource.ProtectedResource$4.call(ProtectedResource.java:173)\r\n        at org.keycloak.authorization.client.resource.ProtectedResource.find(ProtectedResource.java:180)`",
  "reactions": {
    "url": "https://api.github.com/repos/quarkusio/quarkus/issues/36784/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/quarkusio/quarkus/issues/36784/timeline",
  "performed_via_github_app": null,
  "state_reason": "not_planned"
}
