{
  "url": "https://api.github.com/repos/quarkusio/quarkus/issues/36955",
  "repository_url": "https://api.github.com/repos/quarkusio/quarkus",
  "labels_url": "https://api.github.com/repos/quarkusio/quarkus/issues/36955/labels{/name}",
  "comments_url": "https://api.github.com/repos/quarkusio/quarkus/issues/36955/comments",
  "events_url": "https://api.github.com/repos/quarkusio/quarkus/issues/36955/events",
  "html_url": "https://github.com/quarkusio/quarkus/issues/36955",
  "id": 1984047444,
  "node_id": "I_kwDOCFbutM52QilU",
  "number": 36955,
  "title": "`@ServerResponseFilter` with `Throwable` parameter is not called when REST resource is throwing an exception",
  "labels": [
    {
      "id": 985346620,
      "node_id": "MDU6TGFiZWw5ODUzNDY2MjA=",
      "url": "https://api.github.com/repos/quarkusio/quarkus/labels/kind/bug",
      "name": "kind/bug",
      "color": "d73a4a",
      "default": false,
      "description": "Something isn't working"
    },
    {
      "id": 2552031458,
      "node_id": "MDU6TGFiZWwyNTUyMDMxNDU4",
      "url": "https://api.github.com/repos/quarkusio/quarkus/labels/area/rest",
      "name": "area/rest",
      "color": "0366d6",
      "default": false,
      "description": ""
    }
  ],
  "state": "closed",
  "locked": false,
  "milestone": {
    "url": "https://api.github.com/repos/quarkusio/quarkus/milestones/287",
    "html_url": "https://github.com/quarkusio/quarkus/milestone/287",
    "labels_url": "https://api.github.com/repos/quarkusio/quarkus/milestones/287/labels",
    "id": 10182207,
    "node_id": "MI_kwDOCFbutM4Am14_",
    "number": 287,
    "title": "3.2.9.Final",
    "description": "",
    "creator": {
      "login": "aloubyansky",
      "id": 323379,
      "node_id": "MDQ6VXNlcjMyMzM3OQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/323379?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/aloubyansky",
      "html_url": "https://github.com/aloubyansky",
      "followers_url": "https://api.github.com/users/aloubyansky/followers",
      "following_url": "https://api.github.com/users/aloubyansky/following{/other_user}",
      "gists_url": "https://api.github.com/users/aloubyansky/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/aloubyansky/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/aloubyansky/subscriptions",
      "organizations_url": "https://api.github.com/users/aloubyansky/orgs",
      "repos_url": "https://api.github.com/users/aloubyansky/repos",
      "events_url": "https://api.github.com/users/aloubyansky/events{/privacy}",
      "received_events_url": "https://api.github.com/users/aloubyansky/received_events",
      "type": "User",
      "site_admin": false
    },
    "open_issues": 0,
    "closed_issues": 19,
    "state": "closed",
    "created_at": "2023-11-13T21:00:09Z",
    "updated_at": "2023-11-17T15:57:54Z",
    "due_on": "2023-11-15T08:00:00Z",
    "closed_at": "2023-11-17T15:57:54Z"
  },
  "comments": 1,
  "created_at": "2023-11-08T17:07:14Z",
  "updated_at": "2023-11-14T11:54:13Z",
  "closed_at": "2023-11-10T15:30:44Z",
  "active_lock_reason": null,
  "body": "### Describe the bug\r\n\r\nhttps://quarkus.io/guides/resteasy-reactive#request-or-response-filters\r\n![image](https://github.com/quarkusio/quarkus/assets/22860528/1c0fe318-3d74-481c-9e36-601693a281a0)\r\nimplies that a `@ServerResponseFilter` method can handle exceptions, but that does not seem to be the case (see reproducer).\r\n\r\n### Expected behavior\r\n\r\nFilter method should be called with the exception that was thrown in a rest resource method.\r\n\r\n### Actual behavior\r\n\r\nFilter is not called with the exception that was thrown in a rest resource method.\r\n\r\n### How to Reproduce?\r\n\r\n- clone https://github.com/famod/quarkus-quickstarts/tree/server-response-filer-exc\r\n- cd opentelemetry-quickstart\r\n- mvn clean install\r\n- testFailEndpoint will fail because the trace-id header is missing (because the filter is not called)\r\n- in `TraceHeaderServerResponseFilter` activate `@ServerExceptionMapper` -> test will pass\r\n\r\n\r\n### Output of `uname -a` or `ver`\r\n\r\n_No response_\r\n\r\n### Output of `java -version`\r\n\r\n_No response_\r\n\r\n### Quarkus version or git rev\r\n\r\n3.5.0 (and current main respectively)\r\n\r\n### Build tool (ie. output of `mvnw --version` or `gradlew --version`)\r\n\r\n_No response_\r\n\r\n### Additional information\r\n\r\n_No response_",
  "reactions": {
    "url": "https://api.github.com/repos/quarkusio/quarkus/issues/36955/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/quarkusio/quarkus/issues/36955/timeline",
  "performed_via_github_app": null,
  "state_reason": "completed"
}
