{
  "url": "https://api.github.com/repos/quarkusio/quarkus/issues/38799",
  "repository_url": "https://api.github.com/repos/quarkusio/quarkus",
  "labels_url": "https://api.github.com/repos/quarkusio/quarkus/issues/38799/labels{/name}",
  "comments_url": "https://api.github.com/repos/quarkusio/quarkus/issues/38799/comments",
  "events_url": "https://api.github.com/repos/quarkusio/quarkus/issues/38799/events",
  "html_url": "https://github.com/quarkusio/quarkus/issues/38799",
  "id": 2136595976,
  "node_id": "I_kwDOCFbutM5_Wd4I",
  "number": 38799,
  "title": "Built-in RestDataPanacheExceptionMapper is not overridable or has higher priority",
  "labels": [
    {
      "id": 985346620,
      "node_id": "MDU6TGFiZWw5ODUzNDY2MjA=",
      "url": "https://api.github.com/repos/quarkusio/quarkus/labels/kind/bug",
      "name": "kind/bug",
      "color": "d73a4a",
      "default": false,
      "description": "Something isn't working"
    },
    {
      "id": 1273026134,
      "node_id": "MDU6TGFiZWwxMjczMDI2MTM0",
      "url": "https://api.github.com/repos/quarkusio/quarkus/labels/area/panache",
      "name": "area/panache",
      "color": "0366d6",
      "default": false,
      "description": ""
    }
  ],
  "state": "closed",
  "locked": false,
  "milestone": null,
  "comments": 5,
  "created_at": "2024-02-15T13:55:25Z",
  "updated_at": "2024-02-16T12:14:27Z",
  "closed_at": "2024-02-16T12:14:27Z",
  "active_lock_reason": null,
  "body": "### Describe the bug\n\nThe PanacheEntityResource implementations throws RestDataPanacheException which is handled by the built-in [io.quarkus.hibernate.orm.rest.data.panache.runtime.RestDataPanacheExceptionMapper](https://github.com/quarkusio/quarkus/blob/main/extensions/panache/hibernate-orm-rest-data-panache/runtime/src/main/java/io/quarkus/hibernate/orm/rest/data/panache/runtime/RestDataPanacheExceptionMapper.java) class. I want to return custom responses for certain types of RestDataPanacheExceptions but my custom ExceptionMapper is used neither in dev mode nor when I run uber jar.\r\n\r\nThis issue is similar to https://github.com/quarkusio/quarkus/issues/7883 but not sure if the fix was specific to all exception mappers or only for NotFoundExceptionMapper.\n\n### Expected behavior\n\nThe custom ExceptionMapper implemented by the user must take precedence.\n\n### Actual behavior\n\nThe custom ExceptionMapper is not used at all. Always Quarkust runs the default RestDataPanacheExceptionMapper.\n\n### How to Reproduce?\n\n1. Create a rest resource extending `PanacheEntityResource` for an entity with generated id\r\n2. Create a custom exception mapper `ExceptionMapper<RestDataPanacheException>`\r\n3. Send a POST request to create an entity with an explicitly defined id\r\n4. Observe that the default RestDataPanacheExceptionMapper is used instead of the custom mapper\n\n### Output of `uname -a` or `ver`\n\nLinux mypc 5.15.0-94-generic #104-Ubuntu SMP Tue Jan 9 15:25:40 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux\n\n### Output of `java -version`\n\njava version \"21.0.1\" 2023-10-17 LTS Java(TM) SE Runtime Environment (build 21.0.1+12-LTS-29) Java HotSpot(TM) 64-Bit Server VM (build 21.0.1+12-LTS-29, mixed mode, sharing)\n\n### Quarkus version or git rev\n\n3.7.2\n\n### Build tool (ie. output of `mvnw --version` or `gradlew --version`)\n\nApache Maven 3.9.6\n\n### Additional information\n\n_No response_",
  "reactions": {
    "url": "https://api.github.com/repos/quarkusio/quarkus/issues/38799/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/quarkusio/quarkus/issues/38799/timeline",
  "performed_via_github_app": null,
  "state_reason": "not_planned"
}
