{
  "url": "https://api.github.com/repos/quarkusio/quarkus/issues/42135",
  "repository_url": "https://api.github.com/repos/quarkusio/quarkus",
  "labels_url": "https://api.github.com/repos/quarkusio/quarkus/issues/42135/labels{/name}",
  "comments_url": "https://api.github.com/repos/quarkusio/quarkus/issues/42135/comments",
  "events_url": "https://api.github.com/repos/quarkusio/quarkus/issues/42135/events",
  "html_url": "https://github.com/quarkusio/quarkus/issues/42135",
  "id": 2429789698,
  "node_id": "I_kwDOCFbutM6Q06YC",
  "number": 42135,
  "title": "Narayana throws an exception when working with the latest MSSQL server",
  "labels": [
    {
      "id": 985346620,
      "node_id": "MDU6TGFiZWw5ODUzNDY2MjA=",
      "url": "https://api.github.com/repos/quarkusio/quarkus/labels/kind/bug",
      "name": "kind/bug",
      "color": "d73a4a",
      "default": false,
      "description": "Something isn't working"
    },
    {
      "id": 1633508165,
      "node_id": "MDU6TGFiZWwxNjMzNTA4MTY1",
      "url": "https://api.github.com/repos/quarkusio/quarkus/labels/area/narayana",
      "name": "area/narayana",
      "color": "0366d6",
      "default": false,
      "description": "Transactions / Narayana"
    }
  ],
  "state": "closed",
  "locked": false,
  "milestone": null,
  "comments": 3,
  "created_at": "2024-07-25T12:03:22Z",
  "updated_at": "2024-08-26T08:03:33Z",
  "closed_at": "2024-08-26T08:03:21Z",
  "active_lock_reason": null,
  "body": "### Describe the bug\n\nI have an application, which uses Quarkus transaction programmatic API. When I run the application with the latest MS SQL server (mcr.microsoft.com/mssql/rhel/server:2022-CU14-rhel-9.1)  it fails when making a transaction in XA mode. At the same time, it works fine with 2022-CU13-rhel-9.1.\r\nSince the version 2022-CU14-rhel-9.1 is where 2022-latest tag points to (and therefore, the one used by Quarkus DevMode), this is going to affect  a lot of users.\n\n### Expected behavior\n\nTransaction passes\n\n### Actual behavior\n\n```\r\n13:54:47,462 INFO  [app] 13:54:46,437 ARJUNA016061: TransactionImple.enlistResource - XAResource.start returned: XAException.XAER_RMERR for < formatId=131077, gtrid_length=38, bqual_length=36, tx_uid=0:ffff0a057e34:b1f7:66a23cfb:2b, node_name=quarkus-qe, branch_uid=0:ffff0a057e34:b1f7:66a23cfb:69, subordinatenodename=null, eis_name=0 >: javax.transaction.xa.XAException: com.microsoft.sqlserver.jdbc.SQLServerException: Failed to create the XA control connection. Error: \"The connection is closed.\"\r\n13:54:47,462 INFO  [app] \tat com.microsoft.sqlserver.jdbc.SQLServerXAResource.dtc_XA_interface(SQLServerXAResource.java:775)\r\n13:54:47,462 INFO  [app] \tat com.microsoft.sqlserver.jdbc.SQLServerXAResource.start(SQLServerXAResource.java:809)\r\n13:54:47,462 INFO  [app] \tat io.quarkus.ts.transactions.recovery.driver.CrashingXAResource.start(CrashingXAResource.java:97)\r\n13:54:47,462 INFO  [app] \tat io.agroal.narayana.BaseXAResource.start(BaseXAResource.java:153)\r\n13:54:47,462 INFO  [app] \tat com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.enlistResource(TransactionImple.java:648)\r\n13:54:47,462 INFO  [app] \tat com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.enlistResource(TransactionImple.java:408)\r\n13:54:47,462 INFO  [app] \tat io.agroal.narayana.NarayanaTransactionIntegration.associate(NarayanaTransactionIntegration.java:120)\r\n13:54:47,462 INFO  [app] \tat io.agroal.pool.ConnectionPool.getConnection(ConnectionPool.java:292)\r\n13:54:47,462 INFO  [app] \tat io.agroal.pool.DataSource.getConnection(DataSource.java:86)\r\n13:54:47,462 INFO  [app] \tat io.agroal.api.AgroalDataSource_EkaD-FEfbv_myExtdBtVX28RsOE_Synthetic_ClientProxy.getConnection(Unknown Source)\r\n13:54:47,462 INFO  [app] \tat io.quarkus.ts.transactions.recovery.TransactionRecoveryService.makeTransactionInternal(TransactionRecoveryService.java:43)\r\n13:54:47,462 INFO  [app] \tat io.quarkus.ts.transactions.recovery.TransactionRecoveryService.makeTransactionInternal(TransactionRecoveryService.java:39)\r\n13:54:47,462 INFO  [app] \tat io.quarkus.ts.transactions.recovery.service.InjectedUserTransactionRecoveryService.withTransaction(InjectedUserTransactionRecoveryService.java:27)\r\n13:54:47,463 INFO  [app] \tat io.quarkus.ts.transactions.recovery.TransactionRecoveryService.makeTransaction(TransactionRecoveryService.java:25)\r\n13:54:47,463 INFO  [app] \tat io.quarkus.ts.transactions.recovery.service.InjectedUserTransactionRecoveryService_ClientProxy.makeTransaction(Unknown Source)\r\n13:54:47,463 INFO  [app] \tat io.quarkus.ts.transactions.recovery.TransactionLogsResource.makeTransaction(TransactionLogsResource.java:53)\r\n13:54:47,463 INFO  [app] \tat io.quarkus.ts.transactions.recovery.TransactionLogsResource$quarkusrestinvoker$makeTransaction_40fe194699cb8d60fafa6ea499679657f4250adb.invoke(Unknown Source)\r\n13:54:47,463 INFO  [app] \tat org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)\r\n13:54:47,463 INFO  [app] \tat io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)\r\n13:54:47,463 INFO  [app] \tat org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)\r\n13:54:47,463 INFO  [app] \tat io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:599)\r\n13:54:47,463 INFO  [app] \tat org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)\r\n13:54:47,463 INFO  [app] \tat org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)\r\n13:54:47,463 INFO  [app] \tat org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)\r\n13:54:47,463 INFO  [app] \tat org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)\r\n13:54:47,463 INFO  [app] \tat org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)\r\n13:54:47,463 INFO  [app] \tat io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\r\n13:54:47,463 INFO  [app] \tat java.base/java.lang.Thread.run(Thread.java:1583)\r\n13:54:47,463 INFO  [app] 13:54:46,437 ARJUNA016138: Failed to enlist XA resource io.agroal.narayana.BaseXAResource@1fd8ede7: jakarta.transaction.SystemException: TransactionImple.enlistResource - XAResource.start ARJUNA016054: could not register transaction: < formatId=131077, gtrid_length=38, bqual_length=36, tx_uid=0:ffff0a057e34:b1f7:66a23cfb:2b, node_name=quarkus-qe, branch_uid=0:ffff0a057e34:b1f7:66a23cfb:69, subordinatenodename=null, eis_name=0 >\r\n13:54:47,463 INFO  [app] \tat com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.enlistResource(TransactionImple.java:709)\r\n13:54:47,463 INFO  [app] \tat com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.enlistResource(TransactionImple.java:408)\r\n13:54:47,463 INFO  [app] \tat io.agroal.narayana.NarayanaTransactionIntegration.associate(NarayanaTransactionIntegration.java:120)\r\n13:54:47,464 INFO  [app] \tat io.agroal.pool.ConnectionPool.getConnection(ConnectionPool.java:292)\r\n13:54:47,464 INFO  [app] \tat io.agroal.pool.DataSource.getConnection(DataSource.java:86)\r\n13:54:47,464 INFO  [app] \tat io.agroal.api.AgroalDataSource_EkaD-FEfbv_myExtdBtVX28RsOE_Synthetic_ClientProxy.getConnection(Unknown Source)\r\n13:54:47,464 INFO  [app] \tat io.quarkus.ts.transactions.recovery.TransactionRecoveryService.makeTransactionInternal(TransactionRecoveryService.java:43)\r\n13:54:47,464 INFO  [app] \tat io.quarkus.ts.transactions.recovery.TransactionRecoveryService.makeTransactionInternal(TransactionRecoveryService.java:39)\r\n13:54:47,464 INFO  [app] \tat io.quarkus.ts.transactions.recovery.service.InjectedUserTransactionRecoveryService.withTransaction(InjectedUserTransactionRecoveryService.java:27)\r\n13:54:47,464 INFO  [app] \tat io.quarkus.ts.transactions.recovery.TransactionRecoveryService.makeTransaction(TransactionRecoveryService.java:25)\r\n13:54:47,464 INFO  [app] \tat io.quarkus.ts.transactions.recovery.service.InjectedUserTransactionRecoveryService_ClientProxy.makeTransaction(Unknown Source)\r\n13:54:47,464 INFO  [app] \tat io.quarkus.ts.transactions.recovery.TransactionLogsResource.makeTransaction(TransactionLogsResource.java:53)\r\n13:54:47,464 INFO  [app] \tat io.quarkus.ts.transactions.recovery.TransactionLogsResource$quarkusrestinvoker$makeTransaction_40fe194699cb8d60fafa6ea499679657f4250adb.invoke(Unknown Source)\r\n13:54:47,464 INFO  [app] \tat org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)\r\n13:54:47,464 INFO  [app] \tat io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)\r\n13:54:47,464 INFO  [app] \tat org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)\r\n13:54:47,464 INFO  [app] \tat io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:599)\r\n13:54:47,464 INFO  [app] \tat org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)\r\n13:54:47,464 INFO  [app] \tat org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)\r\n13:54:47,464 INFO  [app] \tat org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)\r\n13:54:47,464 INFO  [app] \tat org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)\r\n13:54:47,464 INFO  [app] \tat org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)\r\n13:54:47,465 INFO  [app] \tat io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\r\n13:54:47,465 INFO  [app] \tat java.base/java.lang.Thread.run(Thread.java:1583)\r\n13:54:47,465 INFO  [app] 13:54:46,439 HTTP Request to /transaction-logs?rollback=false&executor=INJECTED_USER_TRANSACTION failed, error id: a280e634-dc76-41b7-8d3e-096fc3992ef8-1: java.lang.RuntimeException: java.lang.RuntimeException: java.sql.SQLException: Exception in association of connection to existing transaction\r\n13:54:47,465 INFO  [app] \tat io.quarkus.ts.transactions.recovery.service.InjectedUserTransactionRecoveryService.withTransaction(InjectedUserTransactionRecoveryService.java:31)\r\n13:54:47,465 INFO  [app] \tat io.quarkus.ts.transactions.recovery.TransactionRecoveryService.makeTransaction(TransactionRecoveryService.java:25)\r\n13:54:47,465 INFO  [app] \tat io.quarkus.ts.transactions.recovery.service.InjectedUserTransactionRecoveryService_ClientProxy.makeTransaction(Unknown Source)\r\n13:54:47,465 INFO  [app] \tat io.quarkus.ts.transactions.recovery.TransactionLogsResource.makeTransaction(TransactionLogsResource.java:53)\r\n13:54:47,465 INFO  [app] \tat io.quarkus.ts.transactions.recovery.TransactionLogsResource$quarkusrestinvoker$makeTransaction_40fe194699cb8d60fafa6ea499679657f4250adb.invoke(Unknown Source)\r\n13:54:47,465 INFO  [app] \tat org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)\r\n13:54:47,465 INFO  [app] \tat io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)\r\n13:54:47,465 INFO  [app] \tat org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)\r\n13:54:47,465 INFO  [app] \tat io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:599)\r\n13:54:47,465 INFO  [app] \tat org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)\r\n13:54:47,465 INFO  [app] \tat org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)\r\n13:54:47,465 INFO  [app] \tat org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)\r\n13:54:47,465 INFO  [app] \tat org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)\r\n13:54:47,465 INFO  [app] \tat org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)\r\n13:54:47,465 INFO  [app] \tat io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\r\n13:54:47,465 INFO  [app] \tat java.base/java.lang.Thread.run(Thread.java:1583)\r\n13:54:47,465 INFO  [app] Caused by: java.lang.RuntimeException: java.sql.SQLException: Exception in association of connection to existing transaction\r\n13:54:47,465 INFO  [app] \tat io.quarkus.ts.transactions.recovery.TransactionRecoveryService.makeTransactionInternal(TransactionRecoveryService.java:54)\r\n13:54:47,466 INFO  [app] \tat io.quarkus.ts.transactions.recovery.TransactionRecoveryService.makeTransactionInternal(TransactionRecoveryService.java:39)\r\n13:54:47,466 INFO  [app] \tat io.quarkus.ts.transactions.recovery.service.InjectedUserTransactionRecoveryService.withTransaction(InjectedUserTransactionRecoveryService.java:27)\r\n13:54:47,466 INFO  [app] \t... 15 more\r\n13:54:47,466 INFO  [app] Caused by: java.sql.SQLException: Exception in association of connection to existing transaction\r\n13:54:47,466 INFO  [app] \tat io.agroal.narayana.NarayanaTransactionIntegration.associate(NarayanaTransactionIntegration.java:130)\r\n13:54:47,466 INFO  [app] \tat io.agroal.pool.ConnectionPool.getConnection(ConnectionPool.java:292)\r\n13:54:47,466 INFO  [app] \tat io.agroal.pool.DataSource.getConnection(DataSource.java:86)\r\n13:54:47,466 INFO  [app] \tat io.agroal.api.AgroalDataSource_EkaD-FEfbv_myExtdBtVX28RsOE_Synthetic_ClientProxy.getConnection(Unknown Source)\r\n13:54:47,466 INFO  [app] \tat io.quarkus.ts.transactions.recovery.TransactionRecoveryService.makeTransactionInternal(TransactionRecoveryService.java:43)\r\n13:54:47,466 INFO  [app] \t... 17 more\r\n13:54:47,466 INFO  [app] Caused by: java.sql.SQLException: Unable to enlist connection to existing transaction\r\n13:54:47,466 INFO  [app] \tat io.agroal.narayana.NarayanaTransactionIntegration.associate(NarayanaTransactionIntegration.java:121)\r\n13:54:47,466 INFO  [app] \t... 21 more\r\n13:54:48,634 INFO  [app] Service stopped (Quarkus JVM mode)\r\n\r\n```\n\n### How to Reproduce?\n\n1. ` git clone git@github.com:quarkus-qe/quarkus-test-suite.git && cd quarkus-test-suite`\r\n2. This fails: `mvn clean verify -pl sql-db/narayana-transactions/ -Dit.test=MssqlTransactionGeneralUsageIT -Dquarkus.platform.version=3.12.3 -Dmssql.image=mcr.microsoft.com/mssql/rhel/server:2022-CU14-rhel-9.1 -Dreruns=0`\r\n3. This also fails: `mvn clean verify -pl sql-db/narayana-transactions/ -Dit.test=MssqlTransactionGeneralUsageIT -Dquarkus.platform.version=3.12.3 -Dmssql.image=mcr.microsoft.com/mssql/rhel/server:2022-latest -Dreruns=0`\r\n4. this succeeds `mvn clean verify -pl sql-db/narayana-transactions/ -Dit.test=MssqlTransactionGeneralUsageIT -Dquarkus.platform.version=3.12.3 -Dmssql.image=mcr.microsoft.com/mssql/rhel/server:2022-CU13-rhel-9.1 -Dreruns=0`\n\n### Output of `uname -a` or `ver`\n\n4.18.0-553.5.1.el8_10.x86_64\n\n### Output of `java -version`\n\n17.0.7, vendor: Red Hat, Inc.\n\n### Quarkus version or git rev\n\n3.12.3\n\n### Build tool (ie. output of `mvnw --version` or `gradlew --version`)\n\nApache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)\n\n### Additional information\n\n_No response_",
  "reactions": {
    "url": "https://api.github.com/repos/quarkusio/quarkus/issues/42135/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/quarkusio/quarkus/issues/42135/timeline",
  "performed_via_github_app": null,
  "state_reason": "completed"
}
