{
  "url": "https://api.github.com/repos/quarkusio/quarkus/issues/42281",
  "repository_url": "https://api.github.com/repos/quarkusio/quarkus",
  "labels_url": "https://api.github.com/repos/quarkusio/quarkus/issues/42281/labels{/name}",
  "comments_url": "https://api.github.com/repos/quarkusio/quarkus/issues/42281/comments",
  "events_url": "https://api.github.com/repos/quarkusio/quarkus/issues/42281/events",
  "html_url": "https://github.com/quarkusio/quarkus/issues/42281",
  "id": 2443929677,
  "node_id": "I_kwDOCFbutM6Rq2hN",
  "number": 42281,
  "title": "Error using UriInfo in ResponseExceptionMapper with reasteasy reactive.",
  "labels": [
    {
      "id": 985346626,
      "node_id": "MDU6TGFiZWw5ODUzNDY2MjY=",
      "url": "https://api.github.com/repos/quarkusio/quarkus/labels/kind/question",
      "name": "kind/question",
      "color": "d876e3",
      "default": false,
      "description": "Further information is requested"
    },
    {
      "id": 2552031458,
      "node_id": "MDU6TGFiZWwyNTUyMDMxNDU4",
      "url": "https://api.github.com/repos/quarkusio/quarkus/labels/area/rest",
      "name": "area/rest",
      "color": "0366d6",
      "default": false,
      "description": ""
    }
  ],
  "state": "closed",
  "locked": false,
  "milestone": null,
  "comments": 7,
  "created_at": "2024-08-02T03:35:06Z",
  "updated_at": "2024-08-02T13:32:56Z",
  "closed_at": "2024-08-02T12:28:21Z",
  "active_lock_reason": null,
  "body": "### Describe the bug\r\n\r\nSince migrating from quarkus 2.16 to quarkus 3.8.5, I started receiving the error `java.util.concurrent.CompletionException: java.lang.IllegalStateException: No RESTEasy Reactive request in progress` I find that this is related to the use of `@Context UriInfo` inside `ResponseExceptionMapper`. To get around this, I created a filter and a RequestScoped class to get the path or pathTemplate that caused the error.  \r\n\r\nThis also happened in the rest and rest-client filters, but I managed to get the path and pathTemplate with some casts but this doesnt smell good, this is the class LogFilter in pathTemplate method at project in how to reproduce section.\r\n\r\n### Expected behavior\r\n\r\nUsing `@Context UriInfo` or `@Context ResourceInfo` without error .\r\n\r\n### Actual behavior\r\n\r\nWhen using `@Context UriInfo or ResourceInfo` in quarkus 3.8.5 with RESTeasy-reactive throw a error `java.util.concurrent.CompletionException: java.lang.IllegalStateException: No RESTEasy Reactive request in progress`\r\n\r\n### How to Reproduce?\r\n\r\nReproducer error :\r\n\r\n1. Clone project from https://github.com/CarlosPanarello/quarkus-rest-problem\r\n2. run with mvn compile quarkus:dev\r\n3. await some seconds\r\n\r\nThis project use scheduler to create users and add then using rest-client, if user id is even it will generate an error that will be catch in ExceptionMapper class, where i`m using UriInfo to get origin path, this class has some TODO where you can change to make this work properly.\r\n\r\n\r\n\r\n\r\n### Output of `uname -a` or `ver`\r\n\r\nLinux ZZAED-FG1234Z1Z 5.15.153.1-microsoft-standard-WSL2 #1 SMP Fri Mar 29 23:14:13 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux\r\n\r\n### Output of `java -version`\r\n\r\nopenjdk version \"21.0.3\" 2024-04-16 LTS\r\n\r\n### Quarkus version or git rev\r\n\r\n3.8.5\r\n\r\n### Build tool (ie. output of `mvnw --version` or `gradlew --version`)\r\n\r\nmvn 3.9.5\r\n\r\n### Additional information\r\n\r\n_No response_",
  "reactions": {
    "url": "https://api.github.com/repos/quarkusio/quarkus/issues/42281/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/quarkusio/quarkus/issues/42281/timeline",
  "performed_via_github_app": null,
  "state_reason": "completed"
}
